-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 14, 2026 at 09:18 AM
-- Server version: 10.11.16-MariaDB-cll-lve
-- PHP Version: 8.4.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mtst2537_pengumuman`
--

-- --------------------------------------------------------

--
-- Table structure for table `access_logs`
--

CREATE TABLE `access_logs` (
  `id` int(10) UNSIGNED NOT NULL,
  `student_id` int(10) UNSIGNED DEFAULT NULL,
  `nisn` varchar(30) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text DEFAULT NULL,
  `accessed_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `access_logs`
--

INSERT INTO `access_logs` (`id`, `student_id`, `nisn`, `ip_address`, `user_agent`, `accessed_at`) VALUES
(1, NULL, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:39:36'),
(2, NULL, '0101501556', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:41:14'),
(3, NULL, '0114214322', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:42:38'),
(4, NULL, '0117513859', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:44:59'),
(5, 102, '0107330736', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:48:04'),
(6, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:50:38'),
(7, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:50:53'),
(8, 111, '0116682755', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 07:51:28'),
(9, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 08:32:51'),
(10, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36', '2026-05-14 08:38:04'),
(11, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:05:57'),
(12, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:06:47'),
(13, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:07:56'),
(14, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36', '2026-05-14 09:08:45'),
(15, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:09:17'),
(16, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:10:09'),
(17, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:16:39'),
(18, 197, '1', '182.1.134.54', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36', '2026-05-14 09:17:24');

-- --------------------------------------------------------

--
-- Table structure for table `admins`
--

CREATE TABLE `admins` (
  `id` int(10) UNSIGNED NOT NULL,
  `username` varchar(60) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama` varchar(120) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `admins`
--

INSERT INTO `admins` (`id`, `username`, `password`, `nama`, `created_at`, `updated_at`) VALUES
(1, 'admin', '$2y$10$Nu35w4pteLfc7BDCIkDPkecjw8wsH8Y2GMfIewUbXLT7zzW6WOxwq', 'Administrator', '2026-05-14 07:36:38', '2026-05-14 07:36:38');

-- --------------------------------------------------------

--
-- Table structure for table `settings`
--

CREATE TABLE `settings` (
  `id` int(10) UNSIGNED NOT NULL,
  `setting_key` varchar(80) NOT NULL,
  `setting_value` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `settings`
--

INSERT INTO `settings` (`id`, `setting_key`, `setting_value`) VALUES
(1, 'announcement_datetime', '2026-05-13 10:00:00'),
(2, 'school_name', 'MTs Negeri 1 Pohuwato'),
(3, 'academic_year', '2025/2026'),
(4, 'drama_duration_normal', '3'),
(5, 'drama_duration_ringan', '10'),
(6, 'drama_duration_sedang', '90'),
(7, 'drama_duration_lucu', '90'),
(8, 'drama_duration_super_tegang', '180');

-- --------------------------------------------------------

--
-- Table structure for table `students`
--

CREATE TABLE `students` (
  `id` int(10) UNSIGNED NOT NULL,
  `nama` varchar(160) NOT NULL,
  `nisn` varchar(30) NOT NULL,
  `tanggal_lahir` date NOT NULL,
  `kelas` varchar(40) NOT NULL,
  `status_kelulusan` varchar(20) NOT NULL DEFAULT 'LULUS',
  `mode_drama` enum('Normal','Drama Ringan','Drama Sedang','Drama Lucu','Drama Super Tegang') NOT NULL DEFAULT 'Normal',
  `pesan_khusus` text DEFAULT NULL,
  `sudah_akses` tinyint(1) NOT NULL DEFAULT 0,
  `jumlah_akses` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `akses_terakhir` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `students`
--

INSERT INTO `students` (`id`, `nama`, `nisn`, `tanggal_lahir`, `kelas`, `status_kelulusan`, `mode_drama`, `pesan_khusus`, `sudah_akses`, `jumlah_akses`, `akses_terakhir`, `created_at`, `updated_at`) VALUES
(100, 'MEYLAN LASATUA', '0103160132', '2010-06-17', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Meylan Lasatua, selamat atas kelulusanmu dari MTsN 1 Pohuwato. Teruslah menjaga akhlak, sebab nilai terbaik seorang lulusan bukan hanya prestasi, tetapi juga sikap yang mulia. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(101, 'YUYIN NUPU', '0117513859', '2011-06-14', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Yuyin Nupu, hari kelulusan ini menjadi bukti bahwa perjuangan dan kesungguhanmu selama di MTsN 1 Pohuwato tidak sia-sia. Semakin jauh langkahmu, semoga semakin kuat pula kerendahan hati dan rasa hormatmu kepada orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(102, 'ENJEL ABDULRAHMAN', '0107330736', '2010-09-24', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Enjel Abdulrahman, kelulusanmu hari ini adalah awal dari perjalanan baru yang lebih luas. Ingatlah bahwa ilmu yang baik akan menuntunmu untuk semakin rendah hati dan menghargai orang lain. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 1, 1, '2026-05-14 07:48:04', '2026-05-14 07:47:21', '2026-05-14 07:48:04'),
(103, 'SALSABILA ALHASNI', '0111036390', '2011-10-29', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Salsabila Alhasni, keluarga besar MTsN 1 Pohuwato turut bangga atas capaian kelulusanmu. Tetaplah sederhana dalam keberhasilan dan kuat dalam menghadapi tantangan berikutnya. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(104, 'AYUDYA FAMALA NUR I. AYUBA', '0103993787', '2010-06-01', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Ayudya Famala Nur I. Ayuba, keberhasilan ini adalah hasil dari doa, usaha, dan ketekunan yang telah kamu jalani. Semoga keberhasilan ini membuatmu semakin dewasa, bijak, dan bertanggung jawab. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(105, 'AL FITRA MULANE', '0109012847', '2010-08-13', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Al Fitra Mulane, selamat melangkah menuju jenjang pendidikan berikutnya dengan penuh keyakinan. Jadilah lulusan yang kuat dalam ilmu, lembut dalam sikap, dan tulus dalam berbuat baik. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(106, 'MOHAMAD AL FADHIEL POLONTALO', '0101501556', '2010-07-19', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Mohamad Al Fadhiel Polontalo, hari ini kamu menutup satu bab penting di MTsN 1 Pohuwato dengan penuh kebanggaan. Tetaplah rendah hati, karena keberhasilan sejati adalah ketika ilmu membuatmu semakin santun dan bermanfaat bagi sesama. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(107, 'PRAMA CHAIRUL JHOSEPH', '0111306686', '2011-03-20', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Prama Chairul Jhoseph, kelulusan ini semoga menjadi pintu pembuka bagi masa depan yang lebih baik. Bawalah nama baik madrasah dengan sikap yang sopan, jujur, dan bertanggung jawab di mana pun kamu berada. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(108, 'LEYDI ADELVIRA', '3113594885', '2011-01-08', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Leydi Adelvira, perjalananmu di MTsN 1 Pohuwato telah memberi banyak pelajaran berharga. Prestasi akan lebih indah jika disertai adab, rasa syukur, dan kepedulian terhadap sesama. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(109, 'NADILLA PUTRI NAZMUDIN', '0108580379', '2010-11-30', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Nadilla Putri Nazmudin, selamat atas pencapaian yang membanggakan ini sebagai lulusan MTsN 1 Pohuwato. Jangan berhenti berbuat baik, karena keberhasilan akan lebih bermakna saat memberi manfaat bagi banyak orang. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(110, 'MOHAMAD SAPUTRA FAIDAH', '3101882725', '2010-09-15', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Mohamad Saputra Faidah, teruslah membawa semangat belajar yang telah tumbuh selama berada di madrasah ini. Gunakan ilmu yang kamu peroleh untuk kebaikan, bukan untuk merasa lebih tinggi dari orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(111, 'AGHUTRIAN KANGO', '0116682755', '2011-05-08', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Aghutrian Kango, kelulusanmu adalah amanah untuk terus menjadi pribadi yang lebih baik. Tetaplah menunduk dalam syukur, lalu bangkit dengan semangat untuk meraih cita-cita yang lebih tinggi. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 1, 1, '2026-05-14 07:51:28', '2026-05-14 07:47:21', '2026-05-14 07:51:28'),
(112, 'YUSUF OLII', '0108493554', '2010-10-08', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Yusuf Olii, semoga momen kelulusan ini menjadi penguat langkahmu dalam meraih cita-cita. Semoga kamu selalu menjaga adab kepada orang tua, guru, teman, dan siapa pun yang kamu temui. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(113, 'FATMAWATI NAYLA TANGAHU', '0119329126', '2011-01-26', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Fatmawati Nayla Tangahu, hari ini menjadi tanda bahwa kamu mampu menyelesaikan proses belajar dengan baik. Jangan biarkan keberhasilan membuatmu tinggi hati; jadikan ia alasan untuk semakin bersyukur dan memperbaiki diri. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(114, 'ADITYA SAMARANG', '3112970187', '2011-01-02', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Aditya Samarang, selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(115, 'SITI FATIYAH SUTRISNO', '0117314111', '2011-10-18', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Siti Fatiyah Sutrisno, capaian ini patut disyukuri sebagai karunia Allah dan buah dari kerja kerasmu. Teruslah menjadi pribadi yang tidak mudah puas, namun tetap santun dalam setiap pencapaian. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(116, 'SELMI ZESKIA MENU', '0117074458', '2011-05-29', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Selmi Zeskia Menu, teruslah menjaga semangat dan adab baik yang telah kamu pelajari di MTsN 1 Pohuwato. Jagalah tutur kata dan perilaku, karena keduanya akan menjadi cerminan baik bagi dirimu dan madrasahmu. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(117, 'SRI APRILIA DJUMA', '0116236082', '2011-04-02', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Sri Aprilia Djuma, kelulusan ini bukan akhir, melainkan awal untuk meraih keberhasilan yang lebih besar. Teruslah melangkah dengan percaya diri, namun jangan pernah kehilangan sikap hormat dan rendah hati. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(118, 'MOHAMAD ABDUL FAZRI PIKOLI', '0114214322', '2011-01-27', 'Kelas 9 - KELAS IX A', 'LULUS', 'Normal', 'Mohamad Abdul Fazri Pikoli, semoga keberhasilan hari ini membuatmu semakin yakin untuk terus belajar dan berprestasi. Jangan lupa bahwa setiap pencapaian lahir dari doa, bimbingan, dan dukungan banyak orang. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(119, 'HUMAIRA ARIF', '3107141887', '2010-08-18', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Humaira Arif, keluarga besar madrasah bangga melihatmu sampai pada tahap kelulusan ini. Buktikan bahwa lulusan madrasah mampu tampil unggul tanpa meninggalkan akhlak yang mulia. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(120, 'MOHAMAD FAKHRI PADUNGGALA', '3111216831', '2011-03-24', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Mohamad Fakhri Padunggala, selamat atas kelulusanmu dari MTsN 1 Pohuwato. Teruslah menjaga akhlak, sebab nilai terbaik seorang lulusan bukan hanya prestasi, tetapi juga sikap yang mulia. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(121, 'MUH. ABDUL HAFIZ MANGOPA', '0103144442', '2010-04-14', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Muh. Abdul Hafiz Mangopa, hari kelulusan ini menjadi bukti bahwa perjuangan dan kesungguhanmu selama di MTsN 1 Pohuwato tidak sia-sia. Semakin jauh langkahmu, semoga semakin kuat pula kerendahan hati dan rasa hormatmu kepada orang lain. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(122, 'HELDY PUTRI HARUN', '0115474103', '2011-05-06', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Heldy Putri Harun, kelulusanmu hari ini adalah awal dari perjalanan baru yang lebih luas. Ingatlah bahwa ilmu yang baik akan menuntunmu untuk semakin rendah hati dan menghargai orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(123, 'NUR FITRIA KALAPATI', '0105042629', '2010-08-25', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Nur Fitria Kalapati, keluarga besar MTsN 1 Pohuwato turut bangga atas capaian kelulusanmu. Tetaplah sederhana dalam keberhasilan dan kuat dalam menghadapi tantangan berikutnya. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(124, 'NOVITA HIZRIA MORA', '0103945628', '2010-11-17', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Novita Hizria Mora, keberhasilan ini adalah hasil dari doa, usaha, dan ketekunan yang telah kamu jalani. Semoga keberhasilan ini membuatmu semakin dewasa, bijak, dan bertanggung jawab. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(125, 'NATASYA PUTRI RAUF', '0118782096', '2011-05-23', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Natasya Putri Rauf, selamat melangkah menuju jenjang pendidikan berikutnya dengan penuh keyakinan. Jadilah lulusan yang kuat dalam ilmu, lembut dalam sikap, dan tulus dalam berbuat baik. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(126, 'ADRIAN KAI', '0119157226', '2011-04-05', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Adrian Kai, hari ini kamu menutup satu bab penting di MTsN 1 Pohuwato dengan penuh kebanggaan. Tetaplah rendah hati, karena keberhasilan sejati adalah ketika ilmu membuatmu semakin santun dan bermanfaat bagi sesama. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(127, 'YOLANDA SALSABILA ABDULLAH', '0118423277', '2011-01-20', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Yolanda Salsabila Abdullah, kelulusan ini semoga menjadi pintu pembuka bagi masa depan yang lebih baik. Bawalah nama baik madrasah dengan sikap yang sopan, jujur, dan bertanggung jawab di mana pun kamu berada. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(128, 'ZIVANA NATASYA S BUNA', '0115686907', '2011-03-31', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Zivana Natasya S Buna, perjalananmu di MTsN 1 Pohuwato telah memberi banyak pelajaran berharga. Prestasi akan lebih indah jika disertai adab, rasa syukur, dan kepedulian terhadap sesama. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(129, 'ALISSA MAYULU', '0104514546', '2010-02-16', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Alissa Mayulu, selamat atas pencapaian yang membanggakan ini sebagai lulusan MTsN 1 Pohuwato. Jangan berhenti berbuat baik, karena keberhasilan akan lebih bermakna saat memberi manfaat bagi banyak orang. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(130, 'APRILIA TINE', '3118065017', '2011-04-11', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Aprilia Tine, teruslah membawa semangat belajar yang telah tumbuh selama berada di madrasah ini. Gunakan ilmu yang kamu peroleh untuk kebaikan, bukan untuk merasa lebih tinggi dari orang lain. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(131, 'ZULKARNAIN MONOARFA', '0102893002', '2010-12-13', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Zulkarnain Monoarfa, kelulusanmu adalah amanah untuk terus menjadi pribadi yang lebih baik. Tetaplah menunduk dalam syukur, lalu bangkit dengan semangat untuk meraih cita-cita yang lebih tinggi. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(132, 'ISMAIL PAKAYA', '0113888127', '2011-02-15', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Ismail Pakaya, semoga momen kelulusan ini menjadi penguat langkahmu dalam meraih cita-cita. Semoga kamu selalu menjaga adab kepada orang tua, guru, teman, dan siapa pun yang kamu temui. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(133, 'MOH. YUDISTIRA ALFARIZHI', '3114273993', '2011-07-27', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Moh. Yudistira Alfarizhi, hari ini menjadi tanda bahwa kamu mampu menyelesaikan proses belajar dengan baik. Jangan biarkan keberhasilan membuatmu tinggi hati; jadikan ia alasan untuk semakin bersyukur dan memperbaiki diri. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(134, 'SITI RAFIKA PUTRI ILAHUDE', '0114005105', '2011-01-16', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Siti Rafika Putri Ilahude, selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(135, 'MOHAMAD FADIL NUSI', '0111487192', '2011-06-10', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Mohamad Fadil Nusi, capaian ini patut disyukuri sebagai karunia Allah dan buah dari kerja kerasmu. Teruslah menjadi pribadi yang tidak mudah puas, namun tetap santun dalam setiap pencapaian. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(136, 'RAIHANNA GHASSANIA MASSIE', '0111140525', '2011-06-16', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Raihanna Ghassania Massie, teruslah menjaga semangat dan adab baik yang telah kamu pelajari di MTsN 1 Pohuwato. Jagalah tutur kata dan perilaku, karena keduanya akan menjadi cerminan baik bagi dirimu dan madrasahmu. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(137, 'VANEZA PUTRI LAMANGGI', '0107803021', '2010-12-01', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Vaneza Putri Lamanggi, kelulusan ini bukan akhir, melainkan awal untuk meraih keberhasilan yang lebih besar. Teruslah melangkah dengan percaya diri, namun jangan pernah kehilangan sikap hormat dan rendah hati. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(138, 'JAHRA KATILI', '0102974211', '2010-11-29', 'Kelas 9 - KELAS IX B', 'LULUS', 'Normal', 'Jahra Katili, semoga keberhasilan hari ini membuatmu semakin yakin untuk terus belajar dan berprestasi. Jangan lupa bahwa setiap pencapaian lahir dari doa, bimbingan, dan dukungan banyak orang. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(139, 'ZAKY PUTRA ABDULLAH', '0111584535', '2011-04-09', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Zaky Putra Abdullah, keluarga besar madrasah bangga melihatmu sampai pada tahap kelulusan ini. Buktikan bahwa lulusan madrasah mampu tampil unggul tanpa meninggalkan akhlak yang mulia. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(140, 'KHALID AZZADILNUL TAHIR', '0101186876', '2010-08-11', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Khalid Azzadilnul Tahir, selamat atas kelulusanmu dari MTsN 1 Pohuwato. Teruslah menjaga akhlak, sebab nilai terbaik seorang lulusan bukan hanya prestasi, tetapi juga sikap yang mulia. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(141, 'RIAN YUNUS', '0109294934', '2010-12-13', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Rian Yunus, hari kelulusan ini menjadi bukti bahwa perjuangan dan kesungguhanmu selama di MTsN 1 Pohuwato tidak sia-sia. Semakin jauh langkahmu, semoga semakin kuat pula kerendahan hati dan rasa hormatmu kepada orang lain. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(142, 'MEILAN BAGU', '0104978929', '2010-05-02', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Meilan Bagu, kelulusanmu hari ini adalah awal dari perjalanan baru yang lebih luas. Ingatlah bahwa ilmu yang baik akan menuntunmu untuk semakin rendah hati dan menghargai orang lain. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(143, 'ALYA RAMADHANI YUSUF', '0104522165', '2010-09-06', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Alya Ramadhani Yusuf, keluarga besar MTsN 1 Pohuwato turut bangga atas capaian kelulusanmu. Tetaplah sederhana dalam keberhasilan dan kuat dalam menghadapi tantangan berikutnya. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(144, 'SITTI AISYAH MOHAMMAD', '0107308923', '2010-12-18', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Sitti Aisyah Mohammad, keberhasilan ini adalah hasil dari doa, usaha, dan ketekunan yang telah kamu jalani. Semoga keberhasilan ini membuatmu semakin dewasa, bijak, dan bertanggung jawab. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(145, 'SRI FEBRIANTI BUSURA', '0119575495', '2011-02-18', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Sri Febrianti Busura, selamat melangkah menuju jenjang pendidikan berikutnya dengan penuh keyakinan. Jadilah lulusan yang kuat dalam ilmu, lembut dalam sikap, dan tulus dalam berbuat baik. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(146, 'MOHAMAD RIFAL ABAS', '0119165387', '2011-06-03', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Mohamad Rifal Abas, hari ini kamu menutup satu bab penting di MTsN 1 Pohuwato dengan penuh kebanggaan. Tetaplah rendah hati, karena keberhasilan sejati adalah ketika ilmu membuatmu semakin santun dan bermanfaat bagi sesama. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(147, 'MERLINDA PAKAYA', '0114001985', '2011-05-27', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Merlinda Pakaya, kelulusan ini semoga menjadi pintu pembuka bagi masa depan yang lebih baik. Bawalah nama baik madrasah dengan sikap yang sopan, jujur, dan bertanggung jawab di mana pun kamu berada. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(148, 'MOHAMMAD FAHRIZAL T. DUNGGIO', '0117984117', '2011-04-29', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Mohammad Fahrizal T. Dunggio, perjalananmu di MTsN 1 Pohuwato telah memberi banyak pelajaran berharga. Prestasi akan lebih indah jika disertai adab, rasa syukur, dan kepedulian terhadap sesama. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(149, 'ANDIKA PRATAMA BUNASI', '0109261949', '2010-11-05', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Andika Pratama Bunasi, selamat atas pencapaian yang membanggakan ini sebagai lulusan MTsN 1 Pohuwato. Jangan berhenti berbuat baik, karena keberhasilan akan lebih bermakna saat memberi manfaat bagi banyak orang. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(150, 'RATNA WATI BIKI', '0114365633', '2011-01-18', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Ratna Wati Biki, teruslah membawa semangat belajar yang telah tumbuh selama berada di madrasah ini. Gunakan ilmu yang kamu peroleh untuk kebaikan, bukan untuk merasa lebih tinggi dari orang lain. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(151, 'SAFIRA JULIANA SALEH', '3113261234', '2011-06-08', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Safira Juliana Saleh, kelulusanmu adalah amanah untuk terus menjadi pribadi yang lebih baik. Tetaplah menunduk dalam syukur, lalu bangkit dengan semangat untuk meraih cita-cita yang lebih tinggi. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(152, 'EMIL HANUNU', '0104548796', '2010-03-09', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Emil Hanunu, semoga momen kelulusan ini menjadi penguat langkahmu dalam meraih cita-cita. Semoga kamu selalu menjaga adab kepada orang tua, guru, teman, dan siapa pun yang kamu temui. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(153, 'SRI ADELIYA USMAN', '0105068233', '2010-07-01', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Sri Adeliya Usman, hari ini menjadi tanda bahwa kamu mampu menyelesaikan proses belajar dengan baik. Jangan biarkan keberhasilan membuatmu tinggi hati; jadikan ia alasan untuk semakin bersyukur dan memperbaiki diri. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(154, 'IFTINNA RAIHANNA TANGAHU', '0118157782', '2011-02-17', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Iftinna Raihanna Tangahu, selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(155, 'SASMITA DEWI DUNGGIO', '0115853023', '2011-06-19', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Sasmita Dewi Dunggio, capaian ini patut disyukuri sebagai karunia Allah dan buah dari kerja kerasmu. Teruslah menjadi pribadi yang tidak mudah puas, namun tetap santun dalam setiap pencapaian. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(156, 'NABILA ISMAIL', '0114963458', '2011-04-30', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Nabila Ismail, teruslah menjaga semangat dan adab baik yang telah kamu pelajari di MTsN 1 Pohuwato. Jagalah tutur kata dan perilaku, karena keduanya akan menjadi cerminan baik bagi dirimu dan madrasahmu. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(157, 'IRSAD DUNGGIO', '0112265186', '2011-04-30', 'Kelas 9 - KELAS IX C', 'LULUS', 'Normal', 'Irsad Dunggio, kelulusan ini bukan akhir, melainkan awal untuk meraih keberhasilan yang lebih besar. Teruslah melangkah dengan percaya diri, namun jangan pernah kehilangan sikap hormat dan rendah hati. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(158, 'ZULKIFLI S. PIPII', '3109850871', '2010-06-01', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Zulkifli S. Pipii, semoga keberhasilan hari ini membuatmu semakin yakin untuk terus belajar dan berprestasi. Jangan lupa bahwa setiap pencapaian lahir dari doa, bimbingan, dan dukungan banyak orang. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(159, 'ZAINUN AZIS', '0118170046', '2011-01-16', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Zainun Azis, keluarga besar madrasah bangga melihatmu sampai pada tahap kelulusan ini. Buktikan bahwa lulusan madrasah mampu tampil unggul tanpa meninggalkan akhlak yang mulia. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(160, 'NURHALIZAH LUAWO', '0104615983', '2010-12-03', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Nurhalizah Luawo, selamat atas kelulusanmu dari MTsN 1 Pohuwato. Teruslah menjaga akhlak, sebab nilai terbaik seorang lulusan bukan hanya prestasi, tetapi juga sikap yang mulia. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(161, 'YUSNIYATI BATURAPA', '0097831594', '2009-11-02', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Yusniyati Baturapa, hari kelulusan ini menjadi bukti bahwa perjuangan dan kesungguhanmu selama di MTsN 1 Pohuwato tidak sia-sia. Semakin jauh langkahmu, semoga semakin kuat pula kerendahan hati dan rasa hormatmu kepada orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(162, 'SALFA NATAZYA DAUWANGO', '0102949891', '2010-11-25', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Salfa Natazya Dauwango, kelulusanmu hari ini adalah awal dari perjalanan baru yang lebih luas. Ingatlah bahwa ilmu yang baik akan menuntunmu untuk semakin rendah hati dan menghargai orang lain. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(163, 'ARVELL VILDJIANSYAH DJABU', '0103145167', '2010-10-02', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Arvell Vildjiansyah Djabu, keluarga besar MTsN 1 Pohuwato turut bangga atas capaian kelulusanmu. Tetaplah sederhana dalam keberhasilan dan kuat dalam menghadapi tantangan berikutnya. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(164, 'AULIA ZEFANA IYAKU', '0118988420', '2011-08-10', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Aulia Zefana Iyaku, keberhasilan ini adalah hasil dari doa, usaha, dan ketekunan yang telah kamu jalani. Semoga keberhasilan ini membuatmu semakin dewasa, bijak, dan bertanggung jawab. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(165, 'MOH. FAWWAZ SAMARANG', '0101688785', '2010-02-12', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Moh. Fawwaz Samarang, selamat melangkah menuju jenjang pendidikan berikutnya dengan penuh keyakinan. Jadilah lulusan yang kuat dalam ilmu, lembut dalam sikap, dan tulus dalam berbuat baik. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(166, 'NURAIN HUMOLA', '0101626385', '2010-05-10', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Nurain Humola, hari ini kamu menutup satu bab penting di MTsN 1 Pohuwato dengan penuh kebanggaan. Tetaplah rendah hati, karena keberhasilan sejati adalah ketika ilmu membuatmu semakin santun dan bermanfaat bagi sesama. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(167, 'ASTIANI TOWAKA', '0102102103', '2010-09-19', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Astiani Towaka, kelulusan ini semoga menjadi pintu pembuka bagi masa depan yang lebih baik. Bawalah nama baik madrasah dengan sikap yang sopan, jujur, dan bertanggung jawab di mana pun kamu berada. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(168, 'MOH. ELFANDO TALIBANA', '3101767351', '2010-02-04', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Moh. Elfando Talibana, perjalananmu di MTsN 1 Pohuwato telah memberi banyak pelajaran berharga. Prestasi akan lebih indah jika disertai adab, rasa syukur, dan kepedulian terhadap sesama. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(169, 'ANISA ALBAKIR', '0117057293', '2011-04-23', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Anisa Albakir, selamat atas pencapaian yang membanggakan ini sebagai lulusan MTsN 1 Pohuwato. Jangan berhenti berbuat baik, karena keberhasilan akan lebih bermakna saat memberi manfaat bagi banyak orang. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(170, 'DIVA DELVIA ALI', '0103578592', '2010-12-23', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Diva Delvia Ali, teruslah membawa semangat belajar yang telah tumbuh selama berada di madrasah ini. Gunakan ilmu yang kamu peroleh untuk kebaikan, bukan untuk merasa lebih tinggi dari orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(171, 'FIRAWATI SAYEDI', '0109950185', '2010-10-03', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Firawati Sayedi, kelulusanmu adalah amanah untuk terus menjadi pribadi yang lebih baik. Tetaplah menunduk dalam syukur, lalu bangkit dengan semangat untuk meraih cita-cita yang lebih tinggi. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(172, 'MOHAMAD SEPTIAN NUSI', '3108638792', '2010-09-27', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Mohamad Septian Nusi, semoga momen kelulusan ini menjadi penguat langkahmu dalam meraih cita-cita. Semoga kamu selalu menjaga adab kepada orang tua, guru, teman, dan siapa pun yang kamu temui. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(173, 'RIZKI AYUB BATURAPA', '0115731001', '2011-06-12', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Rizki Ayub Baturapa, hari ini menjadi tanda bahwa kamu mampu menyelesaikan proses belajar dengan baik. Jangan biarkan keberhasilan membuatmu tinggi hati; jadikan ia alasan untuk semakin bersyukur dan memperbaiki diri. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(174, 'RAHMIYATI DJUMA', '0113656374', '2011-06-14', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Rahmiyati Djuma, selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(175, 'APRILIA ANTULA', '0115030713', '2011-04-02', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Aprilia Antula, capaian ini patut disyukuri sebagai karunia Allah dan buah dari kerja kerasmu. Teruslah menjadi pribadi yang tidak mudah puas, namun tetap santun dalam setiap pencapaian. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(176, 'MUH. RIZKY A. DJUI', '0116452000', '2011-12-22', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Muh. Rizky A. Djui, teruslah menjaga semangat dan adab baik yang telah kamu pelajari di MTsN 1 Pohuwato. Jagalah tutur kata dan perilaku, karena keduanya akan menjadi cerminan baik bagi dirimu dan madrasahmu. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(177, 'NUR ASYFA TOWALU', '0118222984', '2011-03-14', 'Kelas 9 - KELAS IX D', 'LULUS', 'Normal', 'Nur Asyfa Towalu, kelulusan ini bukan akhir, melainkan awal untuk meraih keberhasilan yang lebih besar. Teruslah melangkah dengan percaya diri, namun jangan pernah kehilangan sikap hormat dan rendah hati. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(178, 'KLARISKA BOTUTIHE', '0113045380', '2011-02-06', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Klariska Botutihe, semoga keberhasilan hari ini membuatmu semakin yakin untuk terus belajar dan berprestasi. Jangan lupa bahwa setiap pencapaian lahir dari doa, bimbingan, dan dukungan banyak orang. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(179, 'RAMDAN MARJUN', '0105837680', '2010-08-17', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Ramdan Marjun, keluarga besar madrasah bangga melihatmu sampai pada tahap kelulusan ini. Buktikan bahwa lulusan madrasah mampu tampil unggul tanpa meninggalkan akhlak yang mulia. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(180, 'RAIN RAUF', '0116111234', '2011-04-06', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Rain Rauf, selamat atas kelulusanmu dari MTsN 1 Pohuwato. Teruslah menjaga akhlak, sebab nilai terbaik seorang lulusan bukan hanya prestasi, tetapi juga sikap yang mulia. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(181, 'SASKIYA ISMAIL', '0108037364', '2010-05-11', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Saskiya Ismail, hari kelulusan ini menjadi bukti bahwa perjuangan dan kesungguhanmu selama di MTsN 1 Pohuwato tidak sia-sia. Semakin jauh langkahmu, semoga semakin kuat pula kerendahan hati dan rasa hormatmu kepada orang lain. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(182, 'GIO SAPUTRA YUSUP', '0117888114', '2011-01-27', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Gio Saputra Yusup, kelulusanmu hari ini adalah awal dari perjalanan baru yang lebih luas. Ingatlah bahwa ilmu yang baik akan menuntunmu untuk semakin rendah hati dan menghargai orang lain. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kamu selalu diberi kesehatan, kemudahan belajar, dan keberkahan dalam setiap langkah menuju cita-cita.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(183, 'CINTA RAMADANI ALULU', '0112521127', '2011-07-25', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Cinta Ramadani Alulu, keluarga besar MTsN 1 Pohuwato turut bangga atas capaian kelulusanmu. Tetaplah sederhana dalam keberhasilan dan kuat dalam menghadapi tantangan berikutnya. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah memberkahi ilmumu, memudahkan langkahmu, dan menjadikanmu anak yang berbakti serta bermanfaat bagi agama, keluarga, dan bangsa.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(184, 'AMELIA MUTHMAINNAH BOLILIO', '0113281028', '2011-03-07', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Amelia Muthmainnah Bolilio, keberhasilan ini adalah hasil dari doa, usaha, dan ketekunan yang telah kamu jalani. Semoga keberhasilan ini membuatmu semakin dewasa, bijak, dan bertanggung jawab. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga masa depanmu dipenuhi keberhasilan yang diraih dengan usaha, doa, dan akhlak yang mulia.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(185, 'NUR KHALIZHA HASAN', '3094950352', '2009-10-10', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Nur Khalizha Hasan, selamat melangkah menuju jenjang pendidikan berikutnya dengan penuh keyakinan. Jadilah lulusan yang kuat dalam ilmu, lembut dalam sikap, dan tulus dalam berbuat baik. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga keberhasilan ini menjadi awal dari masa depan yang lebih indah, penuh berkah, dan membawa manfaat untuk banyak orang.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21');
INSERT INTO `students` (`id`, `nama`, `nisn`, `tanggal_lahir`, `kelas`, `status_kelulusan`, `mode_drama`, `pesan_khusus`, `sudah_akses`, `jumlah_akses`, `akses_terakhir`, `created_at`, `updated_at`) VALUES
(186, 'NUR LILLAH MANISA', '0119885767', '2011-03-24', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Nur Lillah Manisa, hari ini kamu menutup satu bab penting di MTsN 1 Pohuwato dengan penuh kebanggaan. Tetaplah rendah hati, karena keberhasilan sejati adalah ketika ilmu membuatmu semakin santun dan bermanfaat bagi sesama. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga Allah menuntunmu kepada jalan yang baik, menjaga adabmu, dan mengangkat derajatmu dengan ilmu yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(187, 'DESY SULISTIANA ALULU', '3104084470', '2010-12-21', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Desy Sulistiana Alulu, kelulusan ini semoga menjadi pintu pembuka bagi masa depan yang lebih baik. Bawalah nama baik madrasah dengan sikap yang sopan, jujur, dan bertanggung jawab di mana pun kamu berada. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah memudahkan pendidikanmu selanjutnya dan menjadikan semua ilmu yang kamu pelajari sebagai amal yang bermanfaat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(188, 'CHAIKAL BUMULO', '3116295221', '2011-01-22', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Chaikal Bumulo, perjalananmu di MTsN 1 Pohuwato telah memberi banyak pelajaran berharga. Prestasi akan lebih indah jika disertai adab, rasa syukur, dan kepedulian terhadap sesama. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga kelulusan ini membawa keberkahan, membuka jalan kebaikan, dan menjadi awal dari prestasi-prestasi berikutnya.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(189, 'NUR RAIHAN H. TABINGO', '3113254687', '2011-05-23', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Nur Raihan H. Tabingo, selamat atas pencapaian yang membanggakan ini sebagai lulusan MTsN 1 Pohuwato. Jangan berhenti berbuat baik, karena keberhasilan akan lebih bermakna saat memberi manfaat bagi banyak orang. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(190, 'MARSYA STEVANI MAYANG', '0107883917', '2010-09-16', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Marsya Stevani Mayang, teruslah membawa semangat belajar yang telah tumbuh selama berada di madrasah ini. Gunakan ilmu yang kamu peroleh untuk kebaikan, bukan untuk merasa lebih tinggi dari orang lain. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah meridai perjalananmu, menguatkan semangat belajarmu, dan menjadikanmu insan yang berguna bagi sesama.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(191, 'ZAHRATUN NISSA ISMAIL', '0112968472', '2011-04-27', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Zahratun Nissa Ismail, kelulusanmu adalah amanah untuk terus menjadi pribadi yang lebih baik. Tetaplah menunduk dalam syukur, lalu bangkit dengan semangat untuk meraih cita-cita yang lebih tinggi. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga setiap langkah setelah kelulusan ini dipenuhi petunjuk Allah, keberkahan ilmu, dan kebahagiaan bagi keluargamu.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(192, 'MOHAMMAD IBRAHIM TULIYABU', '0103445620', '2010-11-14', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Mohammad Ibrahim Tuliyabu, semoga momen kelulusan ini menjadi penguat langkahmu dalam meraih cita-cita. Semoga kamu selalu menjaga adab kepada orang tua, guru, teman, dan siapa pun yang kamu temui. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga setiap ilmu dan pengalaman di MTsN 1 Pohuwato menjadi bekal yang bermanfaat dalam meraih masa depan yang cerah.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(193, 'ABDUL KARIM LADIKU', '0112840906', '2011-02-03', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Abdul Karim Ladiku, hari ini menjadi tanda bahwa kamu mampu menyelesaikan proses belajar dengan baik. Jangan biarkan keberhasilan membuatmu tinggi hati; jadikan ia alasan untuk semakin bersyukur dan memperbaiki diri. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga Allah menjadikanmu pribadi yang cerdas, santun, kuat, dan selalu membawa kebaikan di mana pun berada.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(194, 'KHADIJAH SYANIE TAU\'E', '0109310941', '2010-10-17', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Khadijah Syanie Tau\'e, selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Ingatlah bahwa di balik kelulusanmu ada doa, arahan, dan perhatian dari guru-guru MTsN 1 Pohuwato. Semoga Allah selalu menjaga langkahmu, melapangkan jalan cita-citamu, dan menjadikanmu pribadi yang rendah hati serta berprestasi.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(195, 'RESPATI S.MUDA', '0108129031', '2010-10-08', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Respati S.muda, capaian ini patut disyukuri sebagai karunia Allah dan buah dari kerja kerasmu. Teruslah menjadi pribadi yang tidak mudah puas, namun tetap santun dalam setiap pencapaian. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga ilmu yang kamu bawa menjadi cahaya, menuntunmu untuk sukses dunia dan akhirat.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(196, 'AYATUL HUSNA NENTO', '0103278401', '2010-07-14', 'Kelas 9 - KELAS IX E', 'LULUS', 'Normal', 'Ayatul Husna Nento, teruslah menjaga semangat dan adab baik yang telah kamu pelajari di MTsN 1 Pohuwato. Jagalah tutur kata dan perilaku, karena keduanya akan menjadi cerminan baik bagi dirimu dan madrasahmu. Jangan pernah melupakan guru-gurumu di MTsN 1 Pohuwato yang telah mendampingi proses tumbuh dan belajarmu. Semoga ilmu yang diperoleh menjadi berkah, menguatkan akhlakmu, dan mengantarkanmu menuju masa depan yang penuh kebaikan.', 0, 0, NULL, '2026-05-14 07:47:21', '2026-05-14 07:47:21'),
(197, 'Sawal', '1', '2026-05-13', 'IX A', 'LULUS', 'Normal', 'selamat menjadi alumni MTsN 1 Pohuwato yang siap melangkah lebih jauh. Jadikan kelulusan ini sebagai pengingat untuk terus belajar tanpa merasa paling hebat. Bawalah pesan-pesan baik dari guru-gurumu sebagai pegangan dalam menempuh pendidikan dan kehidupan berikutnya. Semoga kamu tumbuh menjadi alumni yang membanggakan, tetap berakhlak baik, dan selalu dirahmati Allah dalam setiap usaha.', 1, 12, '2026-05-14 09:17:24', '2026-05-14 07:50:19', '2026-05-14 09:17:24');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `access_logs`
--
ALTER TABLE `access_logs`
  ADD PRIMARY KEY (`id`),
  ADD KEY `access_logs_student_id_index` (`student_id`),
  ADD KEY `access_logs_nisn_index` (`nisn`);

--
-- Indexes for table `admins`
--
ALTER TABLE `admins`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `admins_username_unique` (`username`);

--
-- Indexes for table `settings`
--
ALTER TABLE `settings`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `settings_key_unique` (`setting_key`);

--
-- Indexes for table `students`
--
ALTER TABLE `students`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `students_nisn_unique` (`nisn`),
  ADD KEY `students_kelas_index` (`kelas`),
  ADD KEY `students_mode_drama_index` (`mode_drama`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `access_logs`
--
ALTER TABLE `access_logs`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- AUTO_INCREMENT for table `admins`
--
ALTER TABLE `admins`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `settings`
--
ALTER TABLE `settings`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- AUTO_INCREMENT for table `students`
--
ALTER TABLE `students`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=198;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `access_logs`
--
ALTER TABLE `access_logs`
  ADD CONSTRAINT `access_logs_student_fk` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
